---
title: "Data-Wrangling2"
author: "He Jin"
date: "10/23/2017"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(rvest)
library(httr)

```

## Scraping
## Extracting tables
```{r}
url = "http://samhda.s3-us-gov-west-1.amazonaws.com/s3fs-public/field-uploads/2k15StateFiles/NSDUHsaeShortTermCHG2015.htm"
drug_use_xml = read_html(url)

```

That's step one

```{r}
drug_use_xml %>%
  html_nodes(css = "table")
```

```{r}
table_marj = (drug_use_xml %>% html_nodes(css = "table"))[[1]] %>%  ## give me the first one
  html_table() %>%
  .[-1,] %>% 
  as_tibble()
table_marj
```

## class practice
```{r}
url2 = "https://www.bestplaces.net/cost_of_living/city/new_york/new_york"
hotel_xml = read_html(url2)
table_hotel = (hotel_xml %>% html_nodes(css = "table"))[[2]] %>% 
  html_table(header = TRUE)

```

## CSS selectors
I want the names!!

```{r}
url3 = "http://www.imdb.com/title/tt0241527/"

hpss_xml = read_html(url3)

hpss_cast = hpss_xml %>%
  html_nodes(".itemprop .itemprop") %>%
  html_text()

```

```{r}
url4 = "https://www.amazon.com/Philips-Sonicare-rechargeable-toothbrush-HX6211/product-reviews/B00YAR7ZFM/ref=cm_cr_arp_d_viewopt_srt?ie=UTF8&reviewerType=all_reviews&sortBy=recent&pageNumber=1"

toothbrush_xml = read_html(url4)

toothbrush_titles = toothbrush_xml %>% 
  html_nodes(css = "#cm_cr-review_list .review-rating") %>% 
  html_text()

toothbrush_title = toothbrush_xml %>%
  html_nodes(css = "#cm_cr-review_list .review-title") %>%
  html_text()
toothbrush_title
toothbrush_titles
```

## Using an API
### Water use data

Getting the data from API
```{r}
nyc_water = GET("https://data.cityofnewyork.us/resource/waf7-5gvc.csv") %>% 
  content("parsed")
```

Getting the data in json file 
```{r}
nyc_water = GET("https://data.cityofnewyork.us/resource/waf7-5gvc.json") %>% 
  content("text") %>%
  jsonlite::fromJSON() %>%
  as_tibble()
```

### BRFSS
```{r}
brfss = 
  GET("https://chronicdata.cdc.gov/api/views/hn4x-zwk7/rows.csv?accessType=DOWNLOAD") %>% 
  content("parsed")
```

### Catch the pokemon
```{r}
poke = GET("http://pokeapi.co/api/v2/pokemon/1") %>%
  content()
poke$name
poke$abilities
```
